export const hobbies = [
  "Art 🎨",
  "Baking 🧁",
  "Gaming 🎮",
  "Camping ⛺️",
  "Cars 🚗",
  "Cooking 🍳",
  "Dancing 💃",
  "Dogs 🐶",
  "Fishing 🎣",
  "Fitness 🏋️‍♀️",
  "Gardening 🌱",
  "Hiking 🥾",
  "Movies 🎥",
  "Music 🎵",
  "Photography 📸",
  "Reading 📚",
  "Running 🏃‍♀️",
  "Shopping 🛍",
  "Sports ⚽️",
  "Traveling 🧳",
  "Writing ✍️",
  "Yoga 🧘‍♀️",
  "Other...",
];
export const mbti = ["ISTJ", "ISFJ", "INFJ", "INTJ", "ISTP", "ISFP", "INFP", "INTP", "ESTP", "ESFP", "ENFP", "ENTP", "ESTJ", "ESFJ", "ENFJ", "ENTJ"];
export const personality = [
  "Adventurous 🎢",
  "Ambitious 🤓",
  "Analytical 🧐",
  "Artistic 😘",
  "Calm 🙄",
  "Caring 🤗",
  "Cool 🤠",
  "Competitive 😤",
  "Confident 😎",
  "Creative 💡",
  "Curious 🤔",
  "Rich 🤑",
  "Easygoing 😌",
  "Cold 🥶",
  "Energetic 🤪",
  "Extroverted 🤩",
  "Friendly 🤝",
  "Funny 😂",
  "Generous 🥰",
  "Hardworking 🥱",
  "Honest 🤥",
  "Intelligent 🧠",
  "Introverted 🤓",
  "Kind 🥺",
  "Logical 🤓",
  "Loyal 🤗",
  "Optimistic 🤩",
  "Organized ✍️",
  "Outgoing 😉",
  "Passionate 😤",
  "Patient 😑",
  "Quiet 🤐",
  "Reliable 😮",
  "Romantic 😘",
  "Sarcastic 😏",
  "Sensitive 🥺",
  "Serious 😐",
  "Shy 😌",
  "Silly 👻",
  "Spontaneous 🤯",
  "Trustworthy 😇",
  "Witty 😮",
];

export const gender = [
  {
    id: "male",
    label: "🙋🏻‍♂️ Male",
  },
  {
    id: "female",
    label: "🙋🏻‍♀️ Female",
  },
] as const;
